### ISSUE TITLE
Overwrites App Icons and Theme in Manifest

### ISSUE THREAD

**Issue by sabieber** [poovamraj/PinEditTextField#1]
The application Properties `android:icon`, `android:roundIcon` and `android:theme` should be removed from the manifest, as these can cause conflicts.

Wan't to use this library in our app but the mentioned manifest properties result in our app icon getting overwritten by the placeholder on new android versions.

**Comment by poovamraj** [comment]
Hello Thanks for opening this, I will resolve this issue and push the changes right away!

**Comment by poovamraj** [comment]
Hi we have uploaded a version 1.0.2

compile 'com.poovam:pin-edittext-field:1.0.2'

But in the local test clearing the manifest doesn't seem to solve the issue. I am working on this and will update soon with a fix.

**Comment by sabieber** [comment]
Thanks for looking into this issue right away

**Comment by poovamraj** [comment]
Hello,

If you want a quick fix you can use the below line in your Manifest as a workaround. This will replace the label, theme and icon to your current manifest resources.

tools:replace="android:label,android:theme,android:icon"

I'll try to provide a fix for this ASAP

**Comment by poovamraj** [comment]
Please use the new version 'com.poovam:pin-edittext-field:1.0.3'

It is resolved in that build.

I am closing this ticket for now but please feel free to open it again if the issue persists.

Thanks.

**Comment by sabieber** [comment]
Works like a charm. Thanks a lot for fixing it so quickly!
