### ISSUE TITLE
Padding between text and underline

### ISSUE THREAD

**Issue by naivekook** [poovamraj/PinEditTextField#11]
Hello! Thanks for this library.
How can I set padding between text and underline?
My designer wants to do like this https://ibb.co/d9wtY0

**Comment by poovamraj** [comment]
Hi @naivekook I will upload a build with this feature supported by EOD

**Comment by naivekook** [comment]
Hello! Any news?

**Comment by poovamraj** [comment]
Hello,

Sorry, you can see that I am working on a number of issue fixes and features in a new branch. The feature you are asking for is relatively simple and would take few lines of code. I will work it out the coming weekend for sure. Hope you can wait until then.

**Comment by naivekook** [comment]
Great, thanks!

**Comment by poovamraj** [comment]
Hi,

You can find the feature implemented in this version

> compile 'com.poovam:pin-edittext-field:1.1.0'

You can use it on LinePinField like below

> app:bottomTextPaddingDp="15dp"

Thank you for your patience. Do let me know if you need any help.
