### ISSUE TITLE
Circle Fill Space

### ISSUE THREAD

**Issue by shubhamkhuva** [poovamraj/PinEditTextField#14]
How to add Circle Filled Spaces?

**Comment by poovamraj** [comment]
Sorry I dont get you. But the circle gets filled when you type anything. Are you asking for something different?

**Comment by shubhamkhuva** [comment]
Means When i enter something circles filled so i need space between filled color and border

**Comment by poovamraj** [comment]
I am really sorry that feature is not available yet but thats a interesting idea. I will try to implement this in next few days. Ill update you here.

**Comment by shubhamkhuva** [comment]
Yes Thank you so much and Good Work Keep it up😃

**Comment by poovamraj** [comment]
Hey :) 

I have added the feature you asked for in the below version

> compile 'com.poovam:pin-edittext-field:1.1.1'

Use it in the following manner

> app:fillerRadius="2dp"

Thanks for bringing it up. It will be really useful for others too.

![whatsapp image 2018-11-05 at 12 48 32 pm](https://user-images.githubusercontent.com/15910425/47983397-29595900-e0f9-11e8-9174-bf78506d0dac.jpeg)
