### ISSUE TITLE
Add typeface support

### ISSUE THREAD

**Issue by bolotinvl** [poovamraj/PinEditTextField#15]
Adding attribute textStyle in xml doesn't have any effect.

**Comment by poovamraj** [comment]
Hi @bolotinvl 

Thanks for reporting. This should be a simple fix. I will work on it provide it during the weekend. Hope you can wait till then.

Thank you.

**Comment by cabuhatprince** [comment]
Hello, is this available? Thank you so much. :)

**Comment by poovamraj** [comment]
Hi please find it in the below version. And really sorry for the delay. Do open this back if you need any more support

> compile 'com.poovam:pin-edittext-field:1.1.2'

**Comment by Miteshmakwana73** [comment]
@cabuhatprince i am facing same problem how should i change typeface?

**Comment by cabuhatprince** [comment]
> @cabuhatprince i am facing same problem how should i change typeface?

Hello, first create a font in your res folder then add it in your xml app:fontFamily="@font/font_regular" :)
