### ISSUE TITLE
Cursor hides as soon as last item is inserted

### ISSUE THREAD

**Issue by manishng3** [poovamraj/PinEditTextField#17]
The cursor is removed from the pin field as soon as the last digit is entered and the password mask appears without the original input being shown first. The user input should be visible for a short period before being masked with a bullet.

**Comment by poovamraj** [comment]
Hi,

I get the point where you tell about the user input should be visible for a short period before being masked with a bullet. But what about the cursor being removed after the last digit?

I'll try and fix the password problem in maybe next 2-3 weeks. Thank you for raising it :) and have a good 2019.

**Comment by manishng3** [comment]
I meant when the input to the pin field is completed the cursor disappears and it becomes unclear whether the pinView is currently in focus or not. 
Thanks for responding so quickly man and you too have a wonderful 2019.

**Comment by poovamraj** [comment]
Thats intended behaviour. The focus part will be shown through the color of
the field whether its focused or not. You can see the color of the entire
field changes (just like textview) when the focus is lost

**Comment by manishng3** [comment]
But what if one is not using a highlighted field? It feels as if the
pinView has gone out of focus after the last entry.

**Comment by poovamraj** [comment]
Hmmm, I get your point. I can make it in a way that if the highlight is
false, cursor will be there after the last text. But I guess positioning
the cursor after the text wont feel symmetric to the eyes. I'll see what I
can do about it.

**Comment by manishng3** [comment]
Hey man, could you tell me why this pink icon appears on tapping the linePinField after it has been filled completely. This bubble lets the user to paste the pin even when it is disabled.
![device-2018-12-31-100402](https://user-images.githubusercontent.com/43162572/50554604-79acfb80-0ce3-11e9-8660-1b1280e2c1b4.png)

**Comment by poovamraj** [comment]
android:textSelectHandle="@drawable/text_handle"

put this in your xml and it will go away. It is documented in the README

**Comment by manishng3** [comment]
Okay, thanks

**Comment by manishng3** [comment]
Hey man, Happy new year,
Could you give me any hints about making the cursor visible on the last digit of the LinePinField? I tried doing it but was not able to solve it properly. I made some changes in the onDraw method of the LinePinFiled class but it still won't show the cursor on the last field once it is filled with an entry.

**Comment by abbasnaqdi** [comment]
+1

**Comment by ManishaGundapuneedi** [comment]
Hi,

Adding android:textSelectHandle="@drawable/text_handle" to xml didn't solve the issue in my case. The icon is not disappearing. Could you please suggest me a solution?

**Comment by poovamraj** [comment]
Since there will be a text there, I dont think it will be good for the UI to show a handle there.

You can use the following

- `app:fieldColor` - This can be a dim color indicating that view is not in focus
- `app:highlightType="allFields"` This will highlight the view when it comes into focus
-  `app:highlightColor="@color/colorAccent"` This can be used to determine the highlight color

Do let me know if you need any help with this implementation.
