### ISSUE TITLE
Highlighting only completed cells?

### ISSUE THREAD

**Issue by justtwago** [poovamraj/PinEditTextField#18]
Is there any way to highlight only completed cells?

**Comment by poovamraj** [comment]
I'll make the lib more extensible in the next release. will update you soon regarding it

**Comment by poovamraj** [comment]
This feature is provided in the latest version. Please use
 
    implementation 'com.poovam:pin-edittext-field:1.2.0'

Use this your view

        app:highlightType="completedFields"

Do let me know if you need more features. Thank you.
