### ISSUE TITLE
SetBackground each cell

### ISSUE THREAD

**Issue by abdullahsen** [poovamraj/PinEditTextField#20]
Hi,
Great project. Is there a way to fill color only cells?

**Comment by poovamraj** [comment]
Hey, Thanks.

Sorry I am not getting the requirement. Can you elaborate on it.

**Comment by abdullahsen** [comment]
I am using SquarePinField. I want to fill cells with color. 
When i apply app:fieldColor="@color/colorPrimary", it does not work. I wan to paint the each cell with same color. 
How can i fill color cells?

**Comment by poovamraj** [comment]
Now I get it. It is currently not implemented in the library but shouldn't be a big change.. I can implement it in next few weeks when I find time or you can clone the repo and change a single line to implement this. Let me know if you want to clone and change the code I can direct you and maybe you can merge it back into the lib

**Comment by hosseiniSeyRo** [comment]
Is this problem solved?

**Comment by poovamraj** [comment]
I took this up just now. You can expect the fix in next few hours

**Comment by poovamraj** [comment]
Hi, you can find the requested feature in the new version

implementation 'com.poovam:pin-edittext-field:1.2.1'

![Screenshot_1561188408](https://user-images.githubusercontent.com/15910425/59960981-735b4780-94ee-11e9-94b5-df03968d58f3.png)

Sorry for the delay. Hope you guys love the lib. Let me know if you guys need any help.
