### ISSUE TITLE
Logo Proposal

### ISSUE THREAD

**Issue by chimzycash** [poovamraj/PinEditTextField#21]
Hi...
Came across your cool project... As a Logo/Icon Designer who loves to contribute to amazing open source projects, I will love to help contribute to your project by creating a new unique logo that will give your project a unique identity.

At the moment i am working on some idea concepts that i feel you might like and i will update it here once i finish it up so you can give me your feedback and also changes or tweaks you want.

Your response will be appreciated...

Regards!

**Comment by poovamraj** [comment]
Sure :) That's really cool of you. Would love to see the concepts that come up :)

**Comment by chimzycash** [comment]
Awesome... Would finish up the idea concept and send it here for your feedback.

I appreciate your quick response.

**Comment by chimzycash** [comment]
Hello @poovamraj 
Here is my logo idea concept... I would love to read your feedback and also, you can suggest the preferred logo color(s) of your choice.


![LOGO DESIGN_PETF_BACKGROUND_1](https://user-images.githubusercontent.com/37814297/57430967-37fc0680-7229-11e9-815c-a6263c5ed7f0.jpg)
![LOGO DESIGN_PETF_BACKGROUND_2](https://user-images.githubusercontent.com/37814297/57430969-392d3380-7229-11e9-960d-4e3cb38c9c91.jpg)
![LOGO DESIGN_PETF_BACKGROUND_3](https://user-images.githubusercontent.com/37814297/57430970-39c5ca00-7229-11e9-9ef3-b33b9c77def8.jpg)
![LOGO DESIGN_PETF_BACKGROUND_4](https://user-images.githubusercontent.com/37814297/57430971-3a5e6080-7229-11e9-9337-a0ac0832a7b2.jpg)
![LOGO DESIGN_PETF_BACKGROUND_5](https://user-images.githubusercontent.com/37814297/57430973-3af6f700-7229-11e9-85ab-efe82a1c0459.jpg)
![LOGO DESIGN_PETF_idea concept_NEW](https://user-images.githubusercontent.com/37814297/57430976-3b8f8d80-7229-11e9-9199-f42c26a16f75.jpg)

**Comment by poovamraj** [comment]
Hi, Sorry I forgot to reply.

I really like the design and color choice. The concept is beautiful. 

You can add them to README and send a pull request.

You are very talented. Thank you.

**Comment by chimzycash** [comment]
Glad that you like the design... Would prepare all files + vector files and share them for your use.

**Comment by poovamraj** [comment]
Hi,

Is there any portfolio link you could share that I could link in the readme along with your contribution

**Comment by poovamraj** [comment]
Sorry for the delay. I just wanted to make sure that lib didn't undergo any incident like this - https://blog.npmjs.org/post/180565383195/details-about-the-event-stream-incident

Loved your work. Do share any links you want me to add to the Readme :) Thanks for being awesome.

**Comment by chimzycash** [comment]
I really appreciate... Working on a portfolio...
If you have any other open source project that needs a logo design... You can hit me up here and I will be glad to help.

**Comment by chimzycash** [comment]
Here is the Google Drive link to the logo files + Vector files included

https://drive.google.com/drive/folders/1mh_Ip1hEn3scaW_5guU3ZSLOIcJHXQrI?usp=sharing
