### ISSUE TITLE
How to set typeface?

### ISSUE THREAD

**Issue by Miteshmakwana73** [poovamraj/PinEditTextField#23]
@poovamraj 
How should i set typeface?
change font

i am trying this but it's not working
`val font = Typeface.createFromAsset(activity!!.getAssets(), "fonts/sfprotext_heavy.ttf")
        otpedt.typeface = font`

**Comment by poovamraj** [comment]
Hi, 

Sorry for the delay. I will get back to you this weekend.

Thanks

**Comment by poovamraj** [comment]
I took this up just now. I will provide the fix in the next few hours. Sorry for the delay.

**Comment by poovamraj** [comment]
Hi,

This seems to be working properly. You can find the below screenshot
![Screenshot_1561185983](https://user-images.githubusercontent.com/15910425/59960577-c8478f80-94e7-11e9-85b5-3c6af70795f2.png)

Please follow this link - https://developer.android.com/guide/topics/ui/look-and-feel/fonts-in-xml

I am closing this issue for now. Please open it if you have any other queries or need any help.

Thank you :)
