### ISSUE TITLE
Software Keyboard doesn't open

### ISSUE THREAD

**Issue by ChiangChu** [poovamraj/PinEditTextField#26]
Hi,

For Some reason the software keyboard is not opening.
I have the pin field inside a dialog with a constraintLayout and layout_width set to "0dp" for filling the whole width.
The Problem is when I open the dialog I can't get the software keyboard to show up. In the emulator I can at least use the hardware keyboard but thats it.
I can't figure out what I am doing wrong.

` <com.poovam.pinedittextfield.SquarePinField
            android:id="@+id/pin_field"
            android:layout_width="0dp"
            android:layout_height="wrap_content"
            android:layout_marginStart="16dp"
            android:layout_marginTop="8dp"
            android:layout_marginEnd="16dp"
            android:inputType="numberPassword"
            app:layout_constraintBottom_toTopOf="@+id/save_content_mode"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintTop_toBottomOf="@+id/radio_groups"
            app:noOfFields="4"
            app:highlightType="currentField"
            android:textSelectHandle="@null"/>`

These are the configuration regarding the keyboard in the manifest for the activity
`                  android:windowSoftInputMode="adjustPan"
                  android:configChanges="keyboardHidden|orientation|screenSize"`

I hope you can help me.

I am using androidx support library and kotlin 1.3.40

**Comment by ChiangChu** [comment]
The issue was a problem with the dialog and not your framework sorry. I will close this again.
Here the link to the issue regarding the dialog:
https://stackoverflow.com/questions/9102074/android-edittext-in-dialog-doesnt-pull-up-soft-keyboard

**Comment by poovamraj** [comment]
Good one @ChiangChu :)
