### ISSUE TITLE
I tried to make my pin field as a password field, but text is visible

### ISSUE THREAD

**Issue by apnipunL** [poovamraj/PinEditTextField#27]
**Here is the code**

<com.poovam.pinedittextfield.SquarePinField
            android:id="@+id/txtPasscode"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:inputType="numberPassword"
            app:highlightType="completedFields"
            android:textStyle="bold"
            android:textSize="20sp"
            app:cornerRadius="5dp"
            app:noOfFields="4"
            android:textSelectHandle="@drawable/text_handle"
            android:layout_marginBottom="10dp"
            android:layout_marginTop="25dp"/>

**Here is the output**

![Screenshot_20200130-125525](https://user-images.githubusercontent.com/46322757/73428892-4adadc00-4360-11ea-8ff1-0c110684f386.png)

**Comment by poovamraj** [comment]
Sorry, this notification slipped. I will check this out and get back to you in a week

**Comment by fugogugo** [comment]
any update?

**Comment by apnipunL** [comment]
> Sorry, this notification slipped. I will check this out and get back to you in a week

Thank you. Please give me an update. Anyway, I really appreciate your project.

**Comment by touhid1010** [comment]
I also need this feature for ( android:inputType="textPassword") text password.
Please add this feature.
Thanks

**Comment by poovamraj** [comment]
Hey guys, checking on this.

**Comment by poovamraj** [comment]
If it is urgent, you can use 1.2.0, It is only after that version this issue has come. I will try to provide a proper fix sooner

**Comment by poovamraj** [comment]
I fixed it. You can use the following version

implementation 'com.poovam:pin-edittext-field:1.2.3'

Thanks a lot for using the library, do let me know if you need any features. :)
