### ISSUE TITLE
Gradle build warning when using this library

### ISSUE THREAD

**Issue by ColtonIdle** [poovamraj/PinEditTextField#31]
Error: jetified-kotlin-stdlib-jre7-1.2.10.jar: kotlin-stdlib-jre7 is deprecated. Please use kotlin-stdlib-jdk7 instead

```
+--- com.poovam:pin-edittext-field:1.2.1
|    +--- org.jetbrains.kotlin:kotlin-stdlib-jre7:1.2.10
```

Please let me know how to fix or release an udpate

**Comment by poovamraj** [comment]
checking on it

**Comment by poovamraj** [comment]
I see that you are using 1.2.1

Can you try using the latest version

implementation 'com.poovam:pin-edittext-field:1.2.3'

we have increased the stdlib version in it

I am closing it for now. If the issue is not fixed, please feel free to reopen

**Comment by ColtonIdle** [comment]
Didn't fix the issue for me:


Build output
```
    Runtime JAR files in the classpath should have the same version. These files were found in the classpath:
    /Users/coltonidle/.gradle/caches/transforms-2/files-2.1/a9405dd3bd2038225037bd502c82421c/jetified-kotlin-stdlib-jdk8-1.3.61.jar (version 1.3)
    /Users/coltonidle/.gradle/caches/transforms-2/files-2.1/26ae0d67f9d91d153c8bdb468ebe23d7/jetified-kotlin-stdlib-jdk7-1.3.61.jar (version 1.3)
    /Users/coltonidle/.gradle/caches/transforms-2/files-2.1/89a9dd339d1a7508dd3217a910c7f347/jetified-kotlin-stdlib-1.4-M1.jar (version 1.4)
    /Users/coltonidle/.gradle/caches/transforms-2/files-2.1/02d1fe19280b0f35ee050bc84d0e513c/jetified-kotlin-stdlib-common-1.4-M1.jar (version 1.4)
```

And here's a warning in the IDE

<img width="718" alt="Screen Shot 2020-04-20 at 5 57 38 PM" src="https://user-images.githubusercontent.com/31751141/79803696-7c948b00-8330-11ea-8afd-6216fafc9aad.png">

**Comment by poovamraj** [comment]
This doesn't seem to be an issue with the library, Can you change $kotlin_version to 1.4-M1 so that it is same as the plugin version. Currently, it seems to be 1.3.61

**Comment by ColtonIdle** [comment]
$kotlin_version is set to `1.4-M1`

Both of those issues above go away if I remove your dependency. You can go ahead and try a file > new project. See that there's no errors or warnings at build time. Add your dependency, and you get the warning in the build file and a warning in the build output.

![five](https://user-images.githubusercontent.com/31751141/79906976-d5265f80-83e6-11ea-9547-07a376d28d7e.gif)

**Comment by poovamraj** [comment]
Hi,

Can you also share the error you are facing (Apart from the warning) ?

And I could not find kotlin version 1.4-M1 are you using 1.4-M1-release-101 from dev channel? If you are not sure of this, you can just copy paste both your app and project gradle here if possible

and also what happens when you set the kotlin version 1.3.61?

**Comment by ColtonIdle** [comment]
I'm going to try to reproduce in a new project using stable AS instead of canary.

**Comment by ColtonIdle** [comment]
Can't repro with AS stable. Closing for now.

**Comment by alexjorgef** [comment]
@ColtonIdle check [this](https://stackoverflow.com/a/64239440/2042014) reference. solve my warning on canary 10, kotlin 1.5.30

**Comment by RYANFRANKLIN237** [comment]
still facing issues with this library, trying to run a java project and i can't find the 1.2.1 library version, any solution?? @poovamraj 
  here's my error message:
  Failed to resolve: com.poovam:pin-edittext-field:1.2.1
Show in Project Structure dialog
Affected Modules: app
