### ISSUE TITLE
when i close the activity,and its crash,could anyone can help me?

### ISSUE THREAD

**Issue by BananaHuo** [poovamraj/PinEditTextField#33]
<cn.xtwjhz.app.widget.linePinField.LinePinField
            android:id="@+id/verify_Code"
            android:layout_width="0dp"
            android:layout_height="@dimen/dp_40"
            android:layout_marginTop="@dimen/dp_17"
            android:layout_marginEnd="@dimen/dp_37"
            android:textColor="@color/colorBlack"
            android:inputType="number"
            app:isCursorEnabled="true"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintStart_toStartOf="@id/login_Confirm_Title"
            app:layout_constraintTop_toBottomOf="@id/login_Confirm_Title"
            app:noOfFields="4" />

When I finish the Activity.

CRASH:///////////////
 Process: me.jessyan.peach.shop, PID: 16524
    java.lang.IllegalStateException: transformationMethod must not be null
        at cn.xtwjhz.app.widget.linePinField.PinField.getPinFieldTransformation(PinField.kt:316)
        at cn.xtwjhz.app.widget.linePinField.PinField.getCharAt(PinField.kt:308)
        at cn.xtwjhz.app.widget.linePinField.LinePinField.onDraw(LinePinField.kt:55)
        at android.view.View.draw(View.java:20495)

**Comment by poovamraj** [comment]
Hi @BananaHuo 

Since you have closed the ticket, I am assuming it is solved. Can you let me know what caused this crash so that anyone checking out similar issue in future would be benefited. Thanks
