### ISSUE TITLE
Paste menu not appears

### ISSUE THREAD

**Issue by sterien7** [poovamraj/PinEditTextField#35]
I am using the SquarePinField but the Paste Functionality doesn't seem to work.

Any ideas on how I enable it?

**Comment by poovamraj** [comment]
Hi, can you share your xml?

Need to check whether you defined `android:textSelectHandle="@drawable/text_handle"`

Also can you let me know which version of Android are you targeting

**Comment by sterien7** [comment]
I found out that the `android:cursorVisible="false"` was creating the problem so after deleting it all worked. 
Also I am having another issue. a blue line appears under the boxes and I have to set `android:background="@android:color/transparent"` in order to make it disappear. Do you have any idea about that?

**Comment by poovamraj** [comment]
Can you share a screenshot?

**Comment by sterien7** [comment]
Sure
![screenshot](https://user-images.githubusercontent.com/1030014/88324122-85c43800-cd23-11ea-9497-b9f766d967d5.png)

**Comment by sterien7** [comment]
@poovamraj sorry I noticed `app:isCustomBackground="true"` so it means it has to have a background setted

So everything is ok please close the Issue

Thanks

**Comment by poovamraj** [comment]
That's awesome :) Have a good one!
