### ISSUE TITLE
Wrong field size when noOfFields = 2

### ISSUE THREAD

**Issue by riki-dexter** [poovamraj/PinEditTextField#37]
Hi @poovamraj , thanks for this library.
When I use SquarePinField in my activity view with attribute noOfFields = 2, presented field size is wrong. See attached image. With noOfFields greater than 2 all works fine.
![Screenshot_1598449718](https://user-images.githubusercontent.com/1485097/91312811-f04e1500-e7b4-11ea-957c-640fa5a661cd.png)

Here is my code:
`<com.poovam.pinedittextfield.SquarePinField
app:layout_constraintTop_toBottomOf="@+id/text3_1"
app:layout_constraintStart_toStartOf="parent"
app:layout_constraintEnd_toEndOf="parent"
android:layout_width="wrap_content"
android:layout_height="50dp"
android:inputType="number"
android:textSize="20sp"
android:textStyle="bold"
app:cornerRadius="3dp"
app:fieldBgColor="@color/background"
app:noOfFields="2"
app:highlightType="currentField"
app:fieldColor="@color/primaryTextColorUltraLight2"
app:highlightColor="@color/systemBlue"
app:lineThickness="0.5dp"
android:textSelectHandle="@drawable/text_handle"
android:id="@+id/proddate_field_2"
app:isCursorEnabled="true"
android:layout_marginTop="10dp"/>`

Thank you

**Comment by poovamraj** [comment]
Hi @riki-dexter 

I did a quick check in the sample app and it seems to work

![img](https://user-images.githubusercontent.com/15910425/91315854-c9540b00-e7d5-11ea-9c52-c78f1d3ea16d.jpeg)

**Comment by poovamraj** [comment]
Can you just change the noOfFields to 3 in your current layout and share a screenshot?

**Comment by riki-dexter** [comment]
<img width="200" alt="Schermata 2020-08-26 alle 16 38 45" src="https://user-images.githubusercontent.com/1485097/91317744-b4b64980-e7ba-11ea-9868-d282e8994063.png">
Here with noOfFields = 3. I'm in a ConstraintLayout, but also with LinearLayout it doesn't change.
Also setting default attributes such as fieldBgColor, lineThickness still doesn't work.
Thank you

**Comment by riki-dexter** [comment]
Debugging your code of SquarePinField.kt i noticed that in onDraw method paddedX1 and paddedX2 have same value (78.5), and also padding value is 78.5, so total size of the field is 0.
See `val paddedX2 = ((x1+singleFieldWidth)-padding)`
Setting app:distanceInBetween="20dp" as a workaround it works fine, because  padding is no more same as field size.
Setting distanceInBetween="20dp" I have this as result:
<img width="216" alt="Schermata 2020-08-26 alle 17 24 01" src="https://user-images.githubusercontent.com/1485097/91323234-f4802f80-e7c0-11ea-9862-86e281f08d61.png">

**Comment by poovamraj** [comment]
That's a great catch riki. I will check it out and fix it in the next versions.
