### ISSUE TITLE
setTextColor has no effects after initialisation

### ISSUE THREAD

**Issue by dmhl** [poovamraj/PinEditTextField#46]
Layout XML file is the only place when you can set text color.
```
<com.poovam.pinedittextfield.LinePinField
	android:layout_width="match_parent"
	android:layout_height="wrap_content"

	android:textColor="@color/red"
	/>
```

When you try to change text color later (programmatically (from code) or by binding to this property) it will not react to this  change.

Version: 1.2.3

**Comment by poovamraj** [comment]
@dmhl I have merged this to master, I have moved the library to Jitpack since Bintray is closing. You can integrate it using this way


Project level build.gradle

```
allprojects {
	repositories {
		...
		maven { url 'https://jitpack.io' }
	}
}
```

App level build.gradle

```
dependencies {
        implementation 'com.github.poovamraj:PinEditTextField:1.2.5'
}
```
