### ISSUE TITLE
Missing Kotlin jdk8 after removing Jcenter from the project

### ISSUE THREAD

**Issue by AndroidPat** [poovamraj/PinEditTextField#48]
Hi,
My project stopped compiling after I removed Jcenter. I'm using 
    repositories {
        google()
        mavenCentral()
        maven { url 'https://jitpack.io' }
    }
and     implementation 'com.github.poovamraj:PinEditTextField:1.2.5'

The project build fails with the following error:
Could not find org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.4-M1-release-101.
Required by:
         project :app > com.github.poovamraj:PinEditTextField:1.2.5

**Comment by poovamraj** [comment]
Hey @AndroidPat, Is it possible to share your app-level Gradle file here?

**Comment by AndroidPat** [comment]
Hey @poovamraj , thanks for the quick response. Attaching the file.
[build.gradle.txt](https://github.com/poovamraj/PinEditTextField/files/6531157/build.gradle.txt)

**Comment by poovamraj** [comment]
What is the $kotlin_version you are using @AndroidPat?

**Comment by AndroidPat** [comment]
I am unsuccessful with both 1.4.10 and 1.5.0. Android Studio 4.2.1

**Comment by poovamraj** [comment]
@AndroidPat Can you add Kotlin dependency from maven central, you can find the versions here - https://mvnrepository.com/artifact/org.jetbrains.kotlin/kotlin-stdlib-jdk8

**Comment by AndroidPat** [comment]
I am now getting:
Class 'com.poovam.pinedittextfield.LinePinField' is compiled by a pre-release version of Kotlin and cannot be loaded by this version of the compiler
Tested with Kotlin 1.4.10, 1.5.0 and 1.5.10

**Comment by poovamraj** [comment]
Can you invalidate caches and restart Android Studio?

**Comment by AndroidPat** [comment]
Tried it twice and restarted PC - no luck.

**Comment by poovamraj** [comment]
Can you try using the new version of the library?

```implementation 'com.github.poovamraj:PinEditTextField:1.2.6'```

**Comment by poovamraj** [comment]
@AndroidPat I guess the new version should fix the issue. Can you try it out?

**Comment by poovamraj** [comment]
Closing this ticket since new version seems to work for others

**Comment by AndroidPat** [comment]
Sorry for the late response, I was working on another project. The new version works, thank you!
