### ISSUE TITLE
LinePinField's field color is not used when hightlight color is enabled

### ISSUE THREAD

**Issue by raylee4204** [poovamraj/PinEditTextField#5]
Unless I misunderstand what fieldColor is used for, the highlight color overrides the field color when set.

  <com.poovam.pinedittextfield.LinePinField
            android:id="@+id/pin_view"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_marginHorizontal="64dp"
            android:layout_marginTop="32dp"
            android:imeOptions="flagNoFullscreen"
            android:inputType="number"
            android:textColor="@color/text_primary_dark"
            android:textSelectHandle="@drawable/text_handle"
            android:textSize="18sp"
            app:distanceInBetween="12dp"
            app:fieldColor="@color/grey"
            app:highlightColor="@color/grey_dark"
            app:highlightEnabled="true"
            app:lineThickness="1dp"
            app:isCursorEnabled="true"
            app:noOfFields="6" />

**Comment by poovamraj** [comment]
Hello,

Yes you are perfectly right. However you can disable the highlight effect by setting it to false

app:highlightEnabled="false"

Hope this solves the issue.

**Comment by raylee4204** [comment]
I thought the highlight color would be used for the current field that is highlighted as an indicator of where you are

**Comment by poovamraj** [comment]
We currently have cursor for that

app:isCursorEnabled="true"

However if you require that feature. Please let me know and I can provide a build for the same on coming saturday.

**Comment by raylee4204** [comment]
A cursor can be useful and something similar to what I'd like. Just a design choice that is different here. If you can implement it, that'd be great!

**Comment by poovamraj** [comment]
Sure. Ill update the build here on saturday :)

**Comment by poovamraj** [comment]
You can find the feature in the latest version of the library 

compile 'com.poovam:pin-edittext-field:1.0.7'
