### ISSUE TITLE
after adding lib my project cannot build and I am getting this error

### ISSUE THREAD

**Issue by Sardorbekcyber** [poovamraj/PinEditTextField#51]
![image](https://user-images.githubusercontent.com/58398866/120759187-326a6b00-c52c-11eb-9c65-dbf8672f4ec1.png)

**Comment by poovamraj** [comment]
Can you try adding this to plugin block

plugins {
    ...
    id 'kotlin-android-extensions'
}

**Comment by Sardorbekcyber** [comment]
Well build still fails 
![image](https://user-images.githubusercontent.com/58398866/120760235-55e1e580-c52d-11eb-974f-481bfbe69580.png) with this error and also 
when I try to set up onTextComplete listener 
![image](https://user-images.githubusercontent.com/58398866/120760435-8cb7fb80-c52d-11eb-8e03-15a171c86de3.png)

Unresolved reference. None of the following candidates is applicable because of receiver type mismatch: 
public operator fun <T, R> DeepRecursiveFunction<TypeVariable(T), TypeVariable(R)>.invoke(value: TypeVariable(T)): TypeVariable(R) defined in kotlin

Occurs I guess I implement library myself

**Comment by poovamraj** [comment]
Can you try adding this to your dependency? 

```implementation "org.jetbrains.kotlin:kotlin-stdlib:$kotlin_version"```

**Comment by Sardorbekcyber** [comment]
I have implemented library as a seperate modul and updated kotlin and moved android extentions to viewbinding but now everthing works good except onTextCompleteListener

**Comment by poovamraj** [comment]
Can you try using the new library version

```implementation 'com.github.poovamraj:PinEditTextField:1.2.6'```

**Comment by poovamraj** [comment]
Can you let me know if the new version fixes the issue :) I will try to help you fix it if it is still broken

**Comment by Sardorbekcyber** [comment]
Build system work good but when I try to set up onTextComplete listener

Unresolved reference. None of the following candidates is applicable because of receiver type mismatch:
public operator fun <T, R> DeepRecursiveFunction<TypeVariable(T), TypeVariable(R)>.invoke(value: TypeVariable(T)): TypeVariable(R) defined in kotlin  error persists

**Comment by poovamraj** [comment]
Are you setting it up like this?

```       
etPassword.onTextCompleteListener = object : PinField.OnTextCompleteListener{
            override fun onTextComplete(enteredText: String): Boolean {
                Toast.makeText(this@SampleActivity,enteredText, Toast.LENGTH_SHORT).show()
                return@onTextComplete true
            }
        }
```

I see you are calling onTextCompleteListener as a method but it is actually a member variable

**Comment by Sardorbekcyber** [comment]
Thanks for your help and patience it solved my problem
