### ISSUE TITLE
reduce space between circles

### ISSUE THREAD

**Issue by kmno** [poovamraj/PinEditTextField#7]
Hi, i'm using circle pin field and it seems there is a default space between them. and when i set 0dp to to spaceInBetween value in xml, that space is still there. i need to make this smaller. please help me.

thanks #

**Comment by poovamraj** [comment]
Sure. I will look into this and update the status here.

**Comment by poovamraj** [comment]
Hi,
Thanks for being patient and bringing up the issue. It is much appreciated.

I have fixed the issue temporarily in the following build. Please use and let me know

compile 'com.poovam:pin-edittext-field:1.0.8'

**Comment by kmno** [comment]
thanks for your response @poovamraj 
would you please tell me how to reduce the space between circles?

**Comment by poovamraj** [comment]
use distanceInBetween parameter. If you give 0dp, It will be touching each other. Similarly you can provide the distance you want in between the circles

**Comment by kmno** [comment]
i tested that, but there's still a space between them!
it seems it does not respect the distanceInBetween value.

**Comment by poovamraj** [comment]
Are you using the latest version compile 'com.poovam:pin-edittext-field:1.0.8'

Can you send the xml you are using?

**Comment by kmno** [comment]
yes i am using the latest version.

<com.poovam.pinedittextfield.CirclePinField
                android:id="@+id/password_et"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_gravity="center_horizontal"
                android:focusable="false"
                android:focusableInTouchMode="false"
                android:inputType="numberPassword"
                android:textSelectHandle="@drawable/text_handle"
                android:textSize="10sp"
                app:circleRadius="15dp"
                app:distanceInBetween="0dp"
                app:fieldColor="@color/white"
                app:fillerColor="@color/colored_text"
                app:highlightEnabled="true"
                app:noOfFields="4" />

**Comment by poovamraj** [comment]
I am really sorry. Please use this 'com.poovam:pin-edittext-field:1.0.9' . I told 1.0.8 by mistake

**Comment by kmno** [comment]
thank @poovamraj 
it's working fine now. 
but there one another little thing, the circles just stick to the left edge and when i set gravity to center, they all disappear. 
would you please tell me how to center them?

thank you

**Comment by poovamraj** [comment]
Thats the problem I have fixed in 'com.poovam:pin-edittext-field:1.0.10'. You can use this version. If you face problem with respect to half drawn circles. Please try using iscustombackground=true and background=@null

**Comment by poovamraj** [comment]
I will properly fix this issue and update it here. probably ill work on it next weekend

**Comment by kmno** [comment]
thanks my friend.

**Comment by poovamraj** [comment]
Hello :)

I have properly fixed this. You can find it in the below version

> compile 'com.poovam:pin-edittext-field:1.1.0'
