### ISSUE TITLE
It doesn't refresh in fragment

### ISSUE THREAD

**Issue by abdullahsen** [poovamraj/PinEditTextField#8]
I am using it in fragment. When i initialize a new one PinEditTextFiel, its content populates earlier data.

**Comment by poovamraj** [comment]
I am sorry, I don't think I can grasp fully on what's happening. Can you share the piece of code?

**Comment by abdullahsen** [comment]
I solved the problem with creating new instance of fragment. 
But if i come to problem which i hace faced it, I use pinedittextfield in fragment. Also, I have one also textview. When user click one button in fragment, the pinedittextfield text and lenght also text in textview are changing. The pinedittextfiel lenght change successfull but the text which i wrote in it can not disappear.

**Comment by poovamraj** [comment]
Hi Abdul,

I'm happy that you solved the problem. But I guess it would be better just to use the "setText" method and set it empty rather than initiating the fragment fully again. Anyways do let me know if you need any help. I'm closing this issue for now.
