### ISSUE TITLE
Border Radius on Square

### ISSUE THREAD

**Issue by dozieogbo** [poovamraj/PinEditTextField#9]
Would be really nice if it was possible to add backgrounds to each individual item in the square view or any other alternative for adding border radius to the square view.

Really amazing work.

**Comment by poovamraj** [comment]
Currently you can increase the line thickness by using the parameter lineThickness. You can also set background to the whole view by using background attribute with isCustomBackground = true.

If you are asking for a background for just the Feild and not the entire View. Then I will take it into consideration and work on it. 

Thanks.

**Comment by dozieogbo** [comment]
I meant for individual fields.
Either a way to set background radius because in my case, I needed something more curved at the edges or to set a custom background per field.

I am really loving you work.

**Comment by poovamraj** [comment]
Okay now I get it. This is a feature that even I wanted to implement in the library. You can expect this anytime soon. For first I guess I would be providing a feature where you can set the border radius

And thanks a lot for your words. Its really nice of you. :)

**Comment by dozieogbo** [comment]
Great. Thanks.
Meant border radius not background radius :D

**Comment by poovamraj** [comment]
I have finished your feature in CORNER_RADIUS_MASK_PASSWORD. I will upload it as soon as I finish the mask password feature and let you know. It will be ready by the weekend

**Comment by poovamraj** [comment]
Hi,

You can find the feature in below version of the library

> compile 'com.poovam:pin-edittext-field:1.1.0'

Use it like below example on SquarePinField

> app:cornerRadius="10dp"

Let me know if you need any help. Thank for your patience.

![whatsapp image 2018-10-27 at 6 15 20 pm](https://user-images.githubusercontent.com/15910425/47604307-782a3300-da15-11e8-8bf7-064f164ce262.jpeg)
